export const styles = {
  // Restaurant card - w-full mb-4 bg-white rounded-xl shadow-md
  restaurantCard: 'w-full mb-4 bg-white rounded-xl shadow-md',
  restaurantImage: 'w-full h-48 rounded-t-xl',
  restaurantInfo: 'p-4',
  restaurantName: 'text-lg font-semibold text-gray-900 mb-2',
  restaurantDetails: 'flex-row items-center mb-2',
  detailItem: 'flex-row items-center mr-4',
  detailText: 'ml-1 text-sm text-gray-500',
  locationContainer: 'flex-row items-center bg-gray-100 p-2 rounded-md',
  locationText: 'ml-1 text-sm text-gray-500',
  highlightButton: 'p-1',
  highlightedCard: 'border-2 border-blue-400 bg-blue-50',
  restaurantHeader: 'flex-row justify-between items-center px-3 pt-2',
  restaurantCardCompact: 'flex-row h-24 mb-3',
  restaurantCardDetailed: 'mb-6',
  restaurantImageCompact: 'w-24 h-24 rounded-lg',
  restaurantImageDetailed: 'h-60',
  restaurantInfoCompact: 'flex-1 p-3 justify-center',
  restaurantInfoDetailed: 'p-4',
  restaurantNameCompact: 'text-base mb-1',
  restaurantNameDetailed: 'text-2xl mb-2',
  restaurantDescription: 'mt-3 pt-3 border-t border-gray-200',
  descriptionText: 'text-sm text-gray-600 mb-2',
  priceText: 'text-base font-semibold text-green-600 mt-2',
  imageCountBadge: 'absolute bottom-2 right-2 bg-black/60 px-2 py-1 rounded-full',
  imageCountText: 'text-white text-xs font-semibold',
  modalContainer: 'flex-1 bg-black/90 justify-center items-center',
  closeButton: 'absolute top-10 right-5 z-10',
  imageContainer: 'flex-1 w-full flex-row items-center justify-between',
  navButton: 'p-5 z-10',
  fullImage: 'w-full h-full absolute',
}; 