name: Deploy Website & Build Mobile App

on:
  push:
    branches: [main]
    paths:
      - "website/**"
      - "mobile/**"
      - ".github/workflows/deploy.yml"

jobs:
  build-website:
    name: Build & Deploy Website
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm run test

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
            publish_branch: gh-pages

  build-android:
    name: Build & Release Android App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Login to Expo
        run: expo login --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}

      - name: Build APK for Android
        run: expo build:android --no-wait --clear-credentials
        env:
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_CLI_USERNAME: ${{ secrets.EXPO_USERNAME }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: dist/*.apk
